#!/usr/bin/env sh
set -ex

# ===== Setup ENV ===== #
. env
. env.${ENVIRONMENT}

# ===== Build ===== #

# Step 1: setup repository endpoint ${DOCKER_REPOSITORY}

# Step 2: check if already build
# https://stackoverflow.com/questions/32113330/check-if-imagetag-combination-already-exists-on-docker-hub
docker manifest inspect ${IMAGE_NAME}:${GIT_COMMIT_ID} > /dev/null; echo $1
# if already exists skip build

# Step 3: build if needed
docker build ${BUILD_PATH:-./}

# Step 4: tag w/ commit id

# Step 5: tag with environment

# Step 6: tag with tag

# Step 7: push to repository

# Step 8: scan image for sec issue
