#!/usr/bin/env sh
set -ex

# ===== Setup ENV ===== #
. env
. env.${ENVIRONMENT}

# ===== Build ===== #
if [ "${NPM_TOKEN}" != "" ]; then
  echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
fi

npm ci
npm outdated
npm audit
npm run lint
npm test
