- name: Build Application
  type: serial
  services:
    - node
  steps:
    - command: gitflow
    - name: Install Dependencies
      command: npm-ci
    - name: Build Application
      command: npm run build

- name: CI Application
  type: parallel
  services:
    - node
  steps:
    - name: Code Formatting Standard
      command: npm run lint
    # TODO record & compare percent
    - name: Unit & Integration Tests
      command: npm test
    # TODO record & compare count
    - name: OSS - Outdated
      command: npm outdated
    # TODO record & compare count
    - name: OSS - Security
      command: npm audit

    # TODO record & compare count
    - name: Code SAST
      command: echo "TODO"

- name: Save Application Build
  type: serial
  services:
    - aws
  steps:
    - command: echo "TODO"

- name: Deploy Application
  type: serial
  services:
    - aws
  steps:
    - name: Exit if not a deployment branch
      command: bash -c 'if ["${ENVIRONMENT}" == "default"]; then exit 0; fi'

    - name: Deploy Static Assets
      command: SLS_DEBUG=* serverless deploy --verbose --force --stage="api"
