# General Template
# NodeJS: willfarrell/serverless-template
# go: TODO

- name: Setup CI/CD
  type: serial
  service: base
  steps:
    - command: setup-env

- name: Build Application
  type: serial
  service: node
  steps:
    - command: npm-version
    - command: npm-env-check
    - name: Install Dependencies
      command: npm ci

- name: CI Application
  type: parallel
  steps:
    - name: Code - Linting
      service: node
      command: npm run lint
    # TODO record & compare percent
    - name: Unit & Integration Tests
      service: node
      command: npm test
    - name: NPM Networking & Permissions
      service: node
      command: npm doctor
    # TODO record & compare count
    - name: Dependencies - Outdated
      service: node
      command: npm outdated
    # TODO record & compare count
    - name: Dependencies - Security
      service: node
      command: npm audit

- name: Save Application Build
  type: serial
  service: aws
  steps:
    - command: aws-env-check
    - command: aws-auth

- name: Deploy Application
  type: serial
  service: node
  steps:
    - name: Exit if not a deployment branch
      command: sh -c 'if [ "${ENVIRONMENT}" == "" ]; then exit 1; fi'

    - name: Deploy Static Assets
      command: sh -c 'SLS_DEBUG=* serverless deploy --verbose --force --stage="api" --profile="${AWS_DEFAULT_PROFILE}"'
