# General Template
# NodeJS: willfarrell/serverless-template
# go: TODO

- name: Build Application
  type: serial
  service: node
  steps:
    - command: setup-env
    - command: npm-version
    - command: aws-env-check
    - command: npm-env-check
    - name: Install Dependencies
      command: npm ci
    - name: Build Application
      command: npm run build

- name: CI Application
  type: parallel
  service:  node
  steps:
    - name: Code - Linting
      command: npm run lint
    # TODO record & compare percent
    - name: Unit & Integration Tests
      command: npm test
    # TODO record & compare count
    - name: Dependencies - Outdated
      command: npm outdated
    # TODO record & compare count
    - name: Dependencies - Security
      command: npm audit

    # TODO record & compare count
    - name: Code - SAST
      command: echo "TODO"

- name: Save Application Build
  type: serial
  service: aws
  steps:
    - command: echo "TODO"

- name: Deploy Application
  type: serial
  service: node
  steps:
    - name: Exit if not a deployment branch
      command: sh -c 'if ["${ENVIRONMENT}" == "default"]; then exit 1; fi'

    - name: Deploy Static Assets
      command: SLS_DEBUG=* serverless deploy --verbose --force --stage="api"
